# Proyecto riot API

In [ ]:
import numpy 
import pandas as pd

In [ ]:

i = 163
a = numpy.zeros(shape=(i,i))

col = ["Aatrox","Ahri","Akali","Akshan","Alistar","Amumu","Anivia","Annie","Aphelios","Ashe","AurelionSol","Azir","Bard","Belveth","Blitzcrank","Brand","Braum","Caitlyn","Camille","Cassiopeia","Chogath","Corki","Darius","Diana","DrMundo","Draven","Ekko","Elise","Evelynn","Ezreal","FiddleSticks","Fiora","Fizz","Galio","Gangplank","Garen","Gnar","Gragas","Graves","Gwen","Hecarim","Heimerdinger","Illaoi","Irelia","Ivern","Janna","JarvanIV","Jax","Jayce","Jhin","Jinx","Kaisa","Kalista","Karma","Karthus","Kassadin","Katarina","Kayle","Kayn","Kennen","Khazix","Kindred","Kled","KogMaw","KSante","Leblanc","LeeSin","Leona","Lillia","Lissandra","Lucian","Lulu","Lux","MasterYi","Malphite","Malzahar","Maokai","Milio","MissFortune","MonkeyKing","Mordekaiser","Morgana","Nami","Nasus","Nautilus","Neeko","Nidalee","Nilah","Nocturne","Nunu","Olaf","Orianna","Ornn","Pantheon","Poppy","Pyke","Qiyana","Quinn","Rakan","Rammus","RekSai","Rell","Renata","Renekton","Rengar","Riven","Rumble","Ryze","Samira","Sejuani","Senna","Seraphine","Sett","Shaco","Shen","Shyvana","Singed","Sion","Sivir","Skarner","Sona","Soraka","Swain","Sylas","Syndra","TahmKench","Taliyah","Talon","Taric","Teemo","Thresh","Tristana","Trundle","Tryndamere","TwistedFate","Twitch","Udyr","Urgot","Varus","Vayne","Veigar","Velkoz","Vex","Vi","Viego","Viktor","Vladimir","Volibear","Warwick","Xayah","Xerath","XinZhao","Yasuo","Yone","Yorick","Yuumi","Zac","Zed","Zeri","Ziggs","Zilean","Zoe","Zyra"]


print(a)
df = pd.DataFrame(a, columns=col)
df.index = col
print(df)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
         Aatrox  Ahri  Akali  Akshan  Alistar  Amumu  Anivia  Annie  Aphelios  \
Aatrox      0.0   0.0    0.0     0.0      0.0    0.0     0.0    0.0       0.0   
Ahri        0.0   0.0    0.0     0.0      0.0    0.0     0.0    0.0       0.0   
Akali       0.0   0.0    0.0     0.0      0.0    0.0     0.0    0.0       0.0   
Akshan      0.0   0.0    0.0     0.0      0.0    0.0     0.0    0.0       0.0   
Alistar     0.0   0.0    0.0     0.0      0.0    0.0     0.0    0.0       0.0   
...         ...   ...    ...     ...      ...    ...     ...    ...       ...   
Zeri        0.0   0.0    0.0     0.0      0.0    0.0     0.0    0.0       0.0   
Ziggs       0.0   0.0    0.0     0.0      0.0    0.0     0.0    0.0       0.0   
Zilean      0.0   0.0    0.0     0.0      0.0    0.0     0.0    0.0       0.0   
Zoe         0.0   0.0    0.0     0

In [ ]:
ml = pd.read_csv('ml.csv')

In [ ]:
# Planteamiento
print(ml.shape)
ml.info()

(6729, 17)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6729 entries, 0 to 6728
Data columns (total 17 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   game            6729 non-null   object 
 1   top_b_champ     6729 non-null   object 
 2   jgl_b_champ     6729 non-null   object 
 3   mid_b_champ     6729 non-null   object 
 4   mid_b_dmgtaken  6729 non-null   float64
 5   adc_b_champ     6729 non-null   object 
 6   supp_b_champ    6729 non-null   object 
 7   supp_b_vs       6729 non-null   float64
 8   b_win           6729 non-null   bool   
 9   top_r_champ     6729 non-null   object 
 10  jgl_r_champ     6729 non-null   object 
 11  mid_r_champ     6729 non-null   object 
 12  mid_r_dmgtaken  6729 non-null   float64
 13  adc_r_champ     6729 non-null   object 
 14  supp_r_champ    6729 non-null   object 
 15  supp_r_vs       6729 non-null   float64
 16  r_win           6729 non-null   bool   
dtypes: bool(2), float64(4)

In [ ]:
azul = [1,2,3,5,6]
rojo = [9,10,11,13,14]

for iter  in range(len(ml)):

  for i in range (len(azul)):
    ml.iloc[iter, azul[i]] = col.index(ml.iloc[iter, azul[i]]);
    
  for j in range(len(rojo)):
    ml.iloc[iter, rojo[j]] = col.index(ml.iloc[iter, rojo[j]]);

In [ ]:
ml.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6729 entries, 0 to 6728
Data columns (total 17 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   game            6729 non-null   object 
 1   top_b_champ     6729 non-null   object 
 2   jgl_b_champ     6729 non-null   object 
 3   mid_b_champ     6729 non-null   object 
 4   mid_b_dmgtaken  6729 non-null   float64
 5   adc_b_champ     6729 non-null   object 
 6   supp_b_champ    6729 non-null   object 
 7   supp_b_vs       6729 non-null   float64
 8   b_win           6729 non-null   bool   
 9   top_r_champ     6729 non-null   object 
 10  jgl_r_champ     6729 non-null   object 
 11  mid_r_champ     6729 non-null   object 
 12  mid_r_dmgtaken  6729 non-null   float64
 13  adc_r_champ     6729 non-null   object 
 14  supp_r_champ    6729 non-null   object 
 15  supp_r_vs       6729 non-null   float64
 16  r_win           6729 non-null   bool   
dtypes: bool(2), float64(4), object(11

In [ ]:
ml = ml.astype({ 
    'top_b_champ':'int',
    'jgl_b_champ':'int',
    'mid_b_champ':'int',
    'mid_b_dmgtaken':'float64',
    'adc_b_champ':'int',
    'supp_b_champ':'int',
    'supp_b_vs':'float64',
    'b_win':'int',
    'top_r_champ':'int',
    'jgl_r_champ':'int',
    'mid_r_champ':'int',
    'mid_r_dmgtaken':'float64',
    'adc_r_champ':'int',
    'supp_r_champ':'int',
    'supp_r_vs':'float64',
    'r_win':'int',


})

In [ ]:
ml.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6729 entries, 0 to 6728
Data columns (total 17 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   game            6729 non-null   object 
 1   top_b_champ     6729 non-null   int64  
 2   jgl_b_champ     6729 non-null   int64  
 3   mid_b_champ     6729 non-null   int64  
 4   mid_b_dmgtaken  6729 non-null   float64
 5   adc_b_champ     6729 non-null   int64  
 6   supp_b_champ    6729 non-null   int64  
 7   supp_b_vs       6729 non-null   float64
 8   b_win           6729 non-null   int64  
 9   top_r_champ     6729 non-null   int64  
 10  jgl_r_champ     6729 non-null   int64  
 11  mid_r_champ     6729 non-null   int64  
 12  mid_r_dmgtaken  6729 non-null   float64
 13  adc_r_champ     6729 non-null   int64  
 14  supp_r_champ    6729 non-null   int64  
 15  supp_r_vs       6729 non-null   float64
 16  r_win           6729 non-null   int64  
dtypes: float64(4), int64(12), object(

In [ ]:
# Split the dataset intro train and test set
from sklearn.model_selection import train_test_split
train, test = train_test_split(ml, train_size=0.8)

In [ ]:
ml

game  top_b_champ  jgl_b_champ  mid_b_champ  mid_b_dmgtaken  \
0     EUW1_6346459509           53           21          113         45957.0   
1     EUW1_6346412630          152           38          101         33326.0   
2     EUW1_6346372891           74           11           15         31964.0   
3     EUW1_6346361040           58           36           53             0.0   
4     EUW1_6346331917           38           51           77         20241.0   
...               ...          ...          ...          ...             ...   
6724  EUW1_6336898150           32           71          135         34939.0   
6725  EUW1_6336616461           64          144          126         13026.0   
6726  EUW1_6336324526          130           48          113         23002.0   
6727  EUW1_6335902561           31            1           13         19871.0   
6728  EUW1_6335854177           51           89          153          7995.0   

      adc_b_champ  supp_b_champ  supp_b_vs  b_win  top_r_champ  jgl_r_champ  \
0              80           138        0.0      0            2           70   
1              84           159        0.0      1          131           65   
2              78            73        0.0      0          118            7   
3              82            52        0.0      0           68           22   
4             121            13        0.0      0          135           66   
...           ...           ...        ...    ...          ...          ...   
6724           29             5        0.0      1          110          113   
6725          149            84       54.0      1           20          109   
6726           65            74        0.0      1           41           52   
6727           81           121       56.0      1            3           58   
6728          118            72       12.0      0          148           46   

      mid_r_champ  mid_r_dmgtaken  adc_r_champ  supp_r_champ  supp_r_vs  r_win  
0             157         46624.0           34            54        0.0      1  
1              36         38566.0           91           155        0.0      0  
2              21         21471.0           47            76        0.0      1  
3              39          2007.0           23           138        0.0      1  
4             110         19725.0           50            70        0.0      1  
...           ...             ...          ...           ...        ...    ...  
6724          146         58289.0           44            50        0.0      0  
6725          123         16106.0            8            16       34.0      0  
6726          144         39108.0           71             1        0.0      0  
6727           64         17576.0           54            84       37.0      0  
6728           56          7615.0          158           102       24.0      1  

[6729 rows x 17 columns]

In [ ]:
x_train = train.drop(["b_win", "game", "r_win", "mid_b_dmgtaken", "mid_r_dmgtaken", "supp_r_vs", "supp_b_vs"], axis=1)
y_train = train["r_win"] 

In [ ]:
# x_train=np.asarray(x_train).astype(np.int)

# y_train=np.asarray(y_train).astype(np.int)

In [ ]:
x_train

top_b_champ  jgl_b_champ  mid_b_champ  adc_b_champ  supp_b_champ  \
386            48           79           10           51             4   
1696           74           37          152           50           130   
4308           31           37           66          118             9   
2568          129           98           19           29            66   
1893          104           37          116            9            45   
...           ...          ...          ...          ...           ...   
6398           22           89            1          117           110   
478            48           58           10           49           122   
4322           97          143            1          108           120   
1253           90          144           91           50            84   
640            90           40           74           50           130   

      top_r_champ  jgl_r_champ  mid_r_champ  adc_r_champ  supp_r_champ  
386            31           54          131           17            81  
1696           39           16           46           19           135  
4308          154           54           62           50           130  
2568           64           79            1           51            95  
1893           35           86          152           25           130  
...           ...          ...          ...          ...           ...  
6398           97           86           64           51            84  
478           117          113          140          149           155  
4322           57           66            2           49            53  
1253          137           27           48            8            14  
640            20           28            1          149           135  

[5383 rows x 10 columns]

In [ ]:
y_train

386     1
1696    0
4308    0
2568    0
1893    0
       ..
6398    1
478     1
4322    0
1253    0
640     1
Name: r_win, Length: 5383, dtype: int64

In [ ]:
# TensorFlow and tf.keras
import tensorflow as tf

# Helper libraries
import numpy as np
import matplotlib.pyplot as plt

print(tf.__version__)

2.12.0


In [ ]:
model = tf.keras.Sequential([
    tf.keras.layers.Flatten(input_shape=(10, 1)),
    tf.keras.layers.Dense(512, activation='sigmoid'),
    tf.keras.layers.Dense(2)
])

In [ ]:
model.compile(optimizer='adam',
              loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
              metrics=['accuracy'])

In [ ]:
# model = tf.keras.Sequential([
#     tf.keras.layers.Dense(64, input_shape=(11,), activation='relu'),
#     tf.keras.layers.Dense(32, activation='relu'),
#     tf.keras.layers.Dense(10, activation='sigmoid')
# ])

In [ ]:
# model.compile(optimizer='adam',
#               loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
#               metrics=['accuracy'])

In [ ]:
print(x_train)

      top_b_champ  jgl_b_champ  mid_b_champ  adc_b_champ  supp_b_champ  \
386            48           79           10           51             4   
1696           74           37          152           50           130   
4308           31           37           66          118             9   
2568          129           98           19           29            66   
1893          104           37          116            9            45   
...           ...          ...          ...          ...           ...   
6398           22           89            1          117           110   
478            48           58           10           49           122   
4322           97          143            1          108           120   
1253           90          144           91           50            84   
640            90           40           74           50           130   

      top_r_champ  jgl_r_champ  mid_r_champ  adc_r_champ  supp_r_champ  
386            31           54        

In [ ]:
model.fit(x_train, y_train, epochs=100)

Epoch 1/100
169/169 [==============================] - 4s 18ms/step - loss: 0.7127 - accuracy: 0.5176
Epoch 2/100
169/169 [==============================] - 3s 17ms/step - loss: 0.6982 - accuracy: 0.5098
Epoch 3/100
169/169 [==============================] - 4s 23ms/step - loss: 0.7021 - accuracy: 0.5016
Epoch 4/100
169/169 [==============================] - 3s 17ms/step - loss: 0.6946 - accuracy: 0.5216
Epoch 5/100
169/169 [==============================] - 3s 17ms/step - loss: 0.6981 - accuracy: 0.5220
Epoch 6/100
169/169 [==============================] - 3s 17ms/step - loss: 0.6985 - accuracy: 0.5198
Epoch 7/100
169/169 [==============================] - 4s 24ms/step - loss: 0.6996 - accuracy: 0.5194
Epoch 8/100
169/169 [==============================] - 3s 17ms/step - loss: 0.6986 - accuracy: 0.5137
Epoch 9/100
169/169 [==============================] - 3s 17ms/step - loss: 0.6986 - accuracy: 0.5151
Epoch 10/100
169/169 [==============================] - 3s 17ms/step - loss: 0.700

In [ ]:
x_test = train.drop(["b_win", "game", "r_win", "mid_b_dmgtaken", "mid_r_dmgtaken", "supp_r_vs", "supp_b_vs"], axis=1)
y_test = train["r_win"] 

In [ ]:
loss, acc = model.evaluate(x_test, y_test, verbose=2)

print('\nTest loss:', loss)
print('\nTest accuracy:', acc)

169/169 - 1s - loss: 0.4836 - accuracy: 0.7412 - 1s/epoch - 7ms/step

Test loss: 0.4835956394672394

Test accuracy: 0.7412223815917969


In [ ]:
scores = model.predict(x_test)

169/169 [==============================] - 1s 5ms/step


In [ ]:
scores[0]

array([-0.40667218,  0.46923345], dtype=float32)